### ISSUE TITLE
Update website with next event info and post-mortem of 11/1 event.

### ISSUE THREAD

**Issue by zo0o0ot** [nodeschool/wisconsin#2]
We should get stuff updated.  Stale sites aren't fun.

**Comment by jthoms1** [comment]
Looking forward to hearing your post-mortem.

**Comment by zo0o0ot** [comment]
I did post this to my blog, but I don't think it ever made the nodeschool wisconsin site:
http://zootlinux.blogspot.com/2014/12/nodeschool-wisconsin-premiere-event.html

**Comment by zo0o0ot** [comment]
Spoiler alert.  It did, I included a link to my blog.  That seems good enough for me.
